services:
  computer-control:
    build: .
    container_name: computer-control
    ports:
      - "6080:6080"  # noVNC web interface
      - "5000:5000"  # Computer Control API
    volumes:
      - appuser-home:/home/appuser  # Persistent volume for user data
    environment:
      - DISPLAY=:0
      - SCREEN_GEOM=1280x800x24
      - NO_VNC_PORT=6080
      - VNC_PORT=5900
      # Security: VNC password is now required for internet deployment
      - VNC_PASSWORD=${VNC_PASSWORD:?VNC_PASSWORD environment variable is required}
      # Security: API key is required for internet deployment
      - API_KEY=${API_KEY:?API_KEY environment variable is required}
      # System timeouts
      - BASH_TIMEOUT=${BASH_TIMEOUT:-60}
      - SCREENSHOT_TIMEOUT=${SCREENSHOT_TIMEOUT:-10}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:6080/"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

volumes:
  appuser-home:
    driver: local 